export const members = [
  {
    id: 1,
    name: "강민하",
    enName: "MinHaKang",
    github: "m2na7",
    gender: "male",
    role: "YB",
    week1: 6,
    week2: 4,
  },
  {
    id: 2,
    name: "공준혁",
    enName: "JunHyukKong",
    github: "ocahs9",
    gender: "male",
    role: "OB",
    week1: 5,
    week2: 7,
  },
  {
    id: 3,
    name: "곽지욱",
    enName: "JiUgGwag",
    github: "gwagjiug",
    gender: "male",
    role: "YB",
    week1: 9,
    week2: 1,
  },
  {
    id: 4,
    name: "김가연",
    enName: "GaYeonKim",
    github: "ayla_12",
    gender: "female",
    role: "OB",
    week1: 8,
    week2: 7,
  },
  {
    id: 5,
    name: "김가현",
    enName: "GaHyeonKim",
    github: "maylh",
    gender: "female",
    role: "YB",
    week1: 4,
    week2: 8,
  },
  {
    id: 6,
    name: "김건휘",
    enName: "GeonHwiKim",
    github: "KIMGEONHWI",
    gender: "male",
    role: "OB",
    week1: 2,
    week2: 8,
  },
  {
    id: 7,
    name: "김고은",
    enName: "GoEunKim",
    github: "gonn-i",
    gender: "female",
    role: "YB",
    week1: 2,
    week2: 2,
  },
  {
    id: 8,
    name: "김다현",
    enName: "DaHyunKim",
    github: "daahyunk",
    gender: "female",
    role: "YB",
    week1: 5,
    week2: 9,
  },
  {
    id: 9,
    name: "김린아",
    enName: "RinAKim",
    github: "Rinakk",
    gender: "female",
    role: "YB",
    week1: 2,
    week2: 9,
  },
  {
    id: 10,
    name: "김민정",
    enName: "MinJeongKim",
    github: "minjeoong",
    gender: "female",
    role: "YB",
    week1: 4,
    week2: 7,
  },
  {
    id: 11,
    name: "김채은",
    enName: "ChaeEunKim",
    github: "bongtta",
    gender: "female",
    role: "YB",
    week1: 1,
    week2: 5,
  },
  {
    id: 12,
    name: "김채현",
    enName: "ChaeHyunKim",
    github: "imddoy",
    gender: "female",
    role: "OB",
    week1: 8,
    week2: 1,
  },
  {
    id: 13,
    name: "김태욱",
    enName: "TaeWookKim",
    github: "Taew00k",
    gender: "male",
    role: "YB",
    week1: 8,
    week2: 6,
  },
  {
    id: 14,
    name: "김한서",
    enName: "HanSeoKim",
    github: "seueooo",
    gender: "female",
    role: "YB",
    week1: 6,
    week2: 3,
  },
  {
    id: 15,
    name: "노찬영",
    enName: "ChanYoungNoh",
    github: "shroqkf",
    gender: "female",
    role: "YB",
    week1: 9,
    week2: 2,
  },
  {
    id: 16,
    name: "문성희",
    enName: "SeonghuiMoon",
    github: "seong-hui",
    gender: "female",
    role: "OB",
    week1: 9,
    week2: 4,
  },
  {
    id: 17,
    name: "박채연",
    enName: "ChaeYeonPark",
    github: "chaeneey",
    gender: "female",
    role: "OB",
    week1: 1,
    week2: 9,
  },
  {
    id: 18,
    name: "박희선",
    enName: "HeeSunPark",
    github: "heesunee",
    gender: "female",
    role: "YB",
    week1: 3,
    week2: 3,
  },
  {
    id: 19,
    name: "배영경",
    enName: "YoungKyungBae",
    github: "bykbyk0401",
    gender: "female",
    role: "YB",
    week1: 6,
    week2: 2,
  },
  {
    id: 20,
    name: "손지유",
    enName: "JiYooSon",
    github: "zzz-myam",
    gender: "female",
    role: "OB",
    week1: 9,
    week2: 5,
  },
  {
    id: 21,
    name: "유서연",
    enName: "SeoYeonYu",
    github: "youtheyeon",
    gender: "female",
    role: "YB",
    week1: 3,
    week2: 1,
  },
  {
    id: 22,
    name: "유태승",
    enName: "TaeSeungYoo",
    github: "gudusol",
    gender: "male",
    role: "OB",
    week1: 2,
    week2: 2,
  },
  {
    id: 23,
    name: "이예림",
    enName: "YeRimLee",
    github: "yarimu",
    gender: "female",
    role: "OB",
    week1: 4,
    week2: 6,
  },
  {
    id: 24,
    name: "이윤지",
    enName: "YoonJiLee",
    github: "Leeyoonji23",
    gender: "female",
    role: "YB",
    week1: 5,
    week2: 4,
  },
  {
    id: 25,
    name: "이진혁",
    enName: "JinHyeokLee",
    github: "constantly-dev",
    gender: "male",
    role: "YB",
    week1: 1,
    week2: 3,
  },
  {
    id: 26,
    name: "임화랑",
    enName: "HwaRangIm",
    github: "thisishwarang",
    gender: "male",
    role: "OB",
    week1: 3,
    week2: 5,
  },
  {
    id: 27,
    name: "최민",
    enName: "MinChoi",
    github: "Minn-Choi",
    gender: "female",
    role: "YB",
    week1: 1,
    week2: 6,
  },
  {
    id: 28,
    name: "최정완",
    enName: "JungWoanChoi",
    github: "look-back-luca",
    gender: "male",
    role: "YB",
    week1: 4,
    week2: 9,
  },
  {
    id: 29,
    name: "한수정",
    enName: "SooJeongHan",
    github: "hansoojeongsj",
    gender: "female",
    role: "YB",
    week1: 8,
    week2: 8,
  },
];
